### ISSUE TITLE
Power Builder Automation apart from amdocs CSM

### ISSUE THREAD

**Issue by bhavikviks** [Ginger-Automation/Ginger#1233]
**Is your feature request related to a problem? Please describe.**
It's about enhancement. If we can have the PowerBuilder automation feature for custom user apps.

**Describe the solution you'd like**
The way we have MyWebApp if we can have MyPBApp.

**Describe alternatives you've considered**
Currently UFT, IBM rational are some of the tools which allows PowerBuilder automation. It would be great to have an open source tool to automate PowerBuilder apps.

**Comment by MeniKadosh1** [comment]
hi, Ginger is supporting automating PowerBuilder applications it just not offering it in the quick Target Application add window.
Add Windows Target Application and then change it Platform to "PowerBuilder", create also Agent from type "PowerBuilder" map both to same BusinessFlow and automate you application

![image](https://user-images.githubusercontent.com/40244398/65140833-0e918980-da18-11e9-81d8-e3723ad2a42c.png)
