### ISSUE TITLE
unix (Mediation) activities take too long (I'm probably doing something wrong)

### ISSUE THREAD

**Issue by drbombay63** [Ginger-Automation/Ginger#1354]
Using Ginger 3.3

since I wanted to automate Linux command line actions I created a Flow and Activitiy that are linked to the "Mediation" target (this was the only one that indicated Unix as the platform)

examples of some the Actions I've configured within my Activity are :
systemctl restart rsyslog.service
wc -l /var/tmp/someConfigFile| cut -d ' ' -f 1

these are things that return instantly when run on the Linux command line

when I run my Flow from the Ginger GUI they are taking ~30 seconds to execute 
I've tried setting Wait as 0 within the Action Details but this has no impact

any advice would be appreciated
thank you

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JinendraGhodke** [comment]
Can you please share the Screenshot of actions configurations

**Comment by drbombay63** [comment]
Please close this ticket

**Comment by JinendraGhodke** [comment]
Closing based on user response
