### ISSUE TITLE
Cut/Paste item in tree ask user to save

### ISSUE THREAD

**Issue by yaronweiss** [Ginger-Automation/Ginger#15]
When doing cut paste if change have been done without saving the cut is deleting the old file and the new item from memory is save to the target lcoation

Need to ask the user to save before the operation

**Comment by MeniKadosh1** [comment]
need to confirm if issue exist and to improve it

**Comment by JinendraGhodke** [comment]
Feature Request 8631 created for this issue

**Comment by JinendraGhodke** [comment]
This issue is resolved on the latest beta version 3.6.8.
Unsaved changes are saved when doing cut-paste for Repository items
