### ISSUE TITLE
Run a command in File Operations actions error

### ISSUE THREAD

**Issue by bhargavkumar-65** [Ginger-Automation/Ginger#17]
**Describe the bug**
Run a command in File Operations actions error

**To Reproduce**
1. Go to 'Actions -> File Operations Action'
2. Click on 'Operation type -> Run A command'
3. Give Source File path (File name having Spaces)
4. See error :'System can't find the Path specified'

**Expected behavior**
Open the File as per source file path

**Screenshots**
![image](https://user-images.githubusercontent.com/3831436/42317581-5950f8f6-806a-11e8-953b-6d807ca257a7.png)

**Desktop (please complete the following information):**
 - Windows

**Comment by yaronweiss** [comment]
Hi @bhargavkumar-65 
Is this happening only for this specific exe or for any executable?
also - please try a path with no spaces if it will work then it will be a bug we need to fix.
Are you using Windows 10?

**Comment by bhargavkumar-65** [comment]
Hi @yaronweiss 
this is happening for exe, My file path has Spaces. Seems like a bug.
it is working with file name without spaces. I am using Windows 10

Thank you.

**Comment by yaronweiss** [comment]
Hi @bhargavkumar-65 
After looking at the code, the issue is related to searching a space char(" ") which separate the file name and arguments, while in your case it was part of the folder, we will add a fix to supply arguments in another text box so it will support also the case of path with spaces, fix will be in the next beta

**Comment by yulev55** [comment]
Hi
Fix for this issue has been added,
to support file paths that has space/s in their path,
also have been added new input value to provide arguments if needed.

The fix will be available from Ginger Version 3.0.3.3

**Comment by yaronweiss** [comment]
@MeniKadosh1 As discussed please refine the code with @yulev55 , thank you.

**Comment by MeniKadosh1** [comment]
yes, we will do it on Sunday 15/July, thanks.

**Comment by MeniKadosh1** [comment]
fixed.
