### ISSUE TITLE
Ver 3.6 Unable to record for Java application

### ISSUE THREAD

**Issue by rajaselvand** [Ginger-Automation/Ginger#1766]
**Describe the bug**
Ginger ver 3.6 is not recording the test properly for Java application

**Comment by ravirk91** [comment]
Please add more details to investigate the issue.
- JDK version  
- what kind of issue are you facing when recording?  
- Please add error details if you are getting any.

**Comment by ravirk91** [comment]
> Please add more details to investigate the issue.
> 
> * JDK version
> * what kind of issue are you facing when recording?
> * Please add error details if you are getting any.

Please update on above?
