### ISSUE TITLE
Get InnerString

### ISSUE THREAD

**Issue by ravikirankethe** [Ginger-Automation/Ginger#1796]
Like the way we have GetText, GetValue, Get Width etc, can we also have GetInnerString which will pull the entire HTML and save to a variable. In this case, we might want to have the variable length more to save the big content. In our project, we have a requirement to pull the entire string and save them in the database for the descending jobs to take care.

**Comment by ravirk91** [comment]
Hi,

it's supported using "Get Attribute Value" Element Action  "  in UI Element action.

Steps:

- Add UI Element Action
- Select Element Action : "Get Attribute Value"
- Value : "innerHTML"

**Comment by ravirk91** [comment]
Please update on above.
