### ISSUE TITLE
Click Event on Image (Web)

### ISSUE THREAD

**Issue by ravikirankethe** [Ginger-Automation/Ginger#1810]
Can we have a click event on Image (Web)

**Comment by ravirk91** [comment]
Please add more details to reproduce this issue. 
Is it Angular or react based UI? 
Please mention public url where we can reproduce this issue.

**Comment by ravirk91** [comment]
> Please add more details to reproduce this issue.
> Is it Angular or react based UI?
> Please mention public url where we can reproduce this issue.

Could you please update ?
