### ISSUE TITLE
Support : Upload file from window alert pop up for MyWebApp solution

### ISSUE THREAD

**Issue by Anusha1010** [Ginger-Automation/Ginger#1906]
[Support] :

Hi Team,
I created one “MyWebApp” project.I tried uploading files for project from window pop up by using switch window action and file operations (file explorer is opening with title “Google chrome” as icon and “Open” as text) but failed in uploading.There are no help files on this clearly.Please could you help me on this.

**Comment by JinendraGhodke** [comment]
For handling, do not open the file browser.

1. Find the XPath of file input web element using life spy
2. In Ginger directly use set value or send keys and specify file path in the value

**Comment by JinendraGhodke** [comment]
Marking this issue as closed. Please reopen if you still have more queries regarding this.
