### ISSUE TITLE
How to configure Agent for mobile app testing 

### ISSUE THREAD

**Issue by giduturi** [Ginger-Automation/Ginger#3330]
Hello Team, 

Please tell the steps to create agent for mobile automation(Emulator) and how to connect to appium server.

**Comment by ManasiPatil2117** [comment]
Please find steps provided in Ginger by Amdocs documentation-
https://ginger-automation.github.io/Ginger-Web-Help/assets/Ginger_By_Amdocs/Configurations/Agents/Agents_Type_Overview/Mobile_Appium_Agent.htm?rhsearch=appium&rhhlterm=appium%20%E2%80%9Cappium%E2%80%9D
