### ISSUE TITLE
Multi execution of step actions/step based on the number of rows in excel

### ISSUE THREAD

**Issue by Sunny-Teo** [Ginger-Automation/Ginger#667]
**Is your feature request related to a problem? Please describe.**
I am trying to execute a simple test case with two inputs i.e Username and Password. Now, it needs to check this with different set of data from excel. But, I am not able to execute the step multiple times without making a duplicate copy of the step.

**Describe the solution you'd like**
Use the excel column name as variable in the test steps/Step-Action. Based on the number of rows in the excel, repeat the STEP and fetch data on each iteration from excel and pass it to the mapped variables.

More Details:- 
1. Excel contains 3 rows with two columns named as Username and Password.
2. Use the excel column name as variable in Step-Actions> "set text" for username and password.
3. Run the scenario and it should execute 3 times.
4. In first run, username and password should be fetched from first row, in the second run, data should be fetched from second row and so on.

**Describe alternatives you've considered**
I have tried to copy paste step actions and then used two excel action and filtered the inputs. But, it is hectic if we have lot many rows of data to test. 

**Additional context**
Its been couple of days since I am working on ginger. So, if I missed this feature then kindly let me know.

**Comment by MeniKadosh1** [comment]
Hi,

Sorry for late respond.

If I got you right, you just want to iterate over a data set (UserName, Password) values so your generic Automation flow will use unique data set each time.

You have few options to do that, I will describe 2 of those below:
1-	Prepare the Data Source in one of below options:
a.	Use built in Data Source (Recommended)- 
i.	Go to Resources-> Data Sources
ii.	Add Custom table and add “UserName” and “Password” columns to it
iii.	Add data rows to it and save 
![image](https://user-images.githubusercontent.com/40244398/54871451-8ad64780-4dbc-11e9-92bb-5e1d2b3fe7e8.png)
b.	Use Excel sheet with you own columns but add extra column to be used for marking the row as used
2-	Add Actions to pull the data from Source:
a.	In Case you decided to go with built in Data Source  so you do not need special Action for pulling the data
b.	In case you decided to go with Excel so:
i.	Use the Excel Action for pulling the data set and store it into Variables (you supposed to do that in the Action ‘Output Values’ tab)
ii.	Use the “Set Data Used Value” field to mark the row data pulled from in this iteration as “Used”
3-	Run Automation Flow with the Data
a.	In case of Data Source – use Value Expression (“…” button next to input field) for pulling the data from the Data Source table into your Action input field- mark to set the pulled data as “Used”
![image](https://user-images.githubusercontent.com/40244398/54871477-0d5f0700-4dbd-11e9-8ffe-f970c4945e5b.png)

b.	In case of Excel- use Value Expression (“…” button next to input field) for setting the Variable containing the data into the Action input field
4-	Use Flow Control for creating a Loop:
a.	For Data Source- Add “Data Source Action” at end of you flow which will check if extra un used rows exists using the “Flow Control” tab and if extra rows do exists so add Flow Control Action which will create a loop by jumping to the first Action in flow
![image](https://user-images.githubusercontent.com/40244398/54871487-41d2c300-4dbd-11e9-9e11-be24b85dc71a.png)

b.	For Excel you probably will need to add few actions which will do the flow control looping 

For full details, please use latest official release 3.1 + please click F1 to open the Help Library and read about: “Data Source”, “Excel”, “Flow Control”

**Comment by Sunny-Teo** [comment]
Hi MeniKadosh1,
I have tried the data source but getting one problem in implementing it.
I have simplified the scenario to better understand it.
Scenario:- Visit 2 urls based on the URLs fetched from the DB source.

Now, I have followed the above steps but once the two execution is completed there is one more execution that runs and system throws error. Please check the below configuration and error:-
![VE_Snapshot](https://user-images.githubusercontent.com/25932794/54996576-b12ff900-4fef-11e9-8ec3-69ff2be2daa9.PNG)
![EBA_Error](https://user-images.githubusercontent.com/25932794/54996579-b3925300-4fef-11e9-97c7-d086dbadbc9c.PNG)

I have tried with both rerun the step and rerun step-action in flow control. Same error.
Is it a bug or I am doing something wrong. Please suggest.

I am not able to test it with Excel but I will definitely try that.
In the end, thanks for your valuable inputs.

**Comment by MeniKadosh1** [comment]
hi,

Error says that no UnUsed/Available row was found (you can see for both rows 'GINGER_USED' cell is checked)- so it return empty URL and then the Browser Action fails and show Error that URL is not valid (empty).

what you need to do is to add DataSource action on begining/end of the flow which will mark all table rows as Unused so you will be able to run the flow on it again and start from row 1.
see below how to configure that action:
![image](https://user-images.githubusercontent.com/40244398/55031263-e734a380-5016-11e9-934d-5ba87dc3b299.png)

**Comment by Sunny-Teo** [comment]
Hi MeniKadosh1,

Thanks for the inputs. With bit of adjustment in the Flow control and from the above action, i am able to achieve the expected.
