### ISSUE TITLE
Add agent to sub folder not visible/selected

### ISSUE THREAD

**Issue by yaronweiss** [Ginger-Automation/Ginger#7]
**Describe the bug**
After Adding new agent to sub folder the agent tree item is not visible and selected

**To Reproduce**
1. Go to Configuration/Agents
2. Create sub folder
3. Add agent to new sub folder
4. Agent is created but is not visible on the tree

**Expected behavior**
agent is visible and selected

**Comment by MeniKadosh1** [comment]
Fixed.
