### ISSUE TITLE
Run Analyzer - Giving error for existing Model Globlal Parameter

### ISSUE THREAD

**Issue by JaspreetGIT** [Ginger-Automation/Ginger#786]
1. Add a Global Model Parameter in the Business flow.
2. Add a DB Action in the Business flow which is using that Global Parameter as input in Free Sql
e.g. select * from customer WHERE account_id='{GlobalAppsModelsParam Name=<CUSTOMERID>}'
3. Run Analyzer on Business flow

Getting Critical error saying Global Parameter "<CUSTOMERID>}" does not exist

**Comment by MeniKadosh1** [comment]
Bug #7317 was raised for it.

**Comment by vyasprateek** [comment]
Hello @JaspreetGIT , Thank You for reporting the issue, it is fixed in the coming Beta version 3.2.2.
