### ISSUE TITLE
Duplicate the existing api model does not copy the added Global Parameters in Model

### ISSUE THREAD

**Issue by JaspreetGIT** [Ginger-Automation/Ginger#787]
Create an API Model - Model1
Configure to add input from Local and Global Parameter 
Save it.
Duplicate the recently created Model1
Check Model1_Copy Configuration.

Expected:
It should have Local/Global Parameters configured as per original API Model
Actual:
No Mapped Global Parameter availble in list

**Comment by MeniKadosh1** [comment]
have you saved the API model before duplicating it?

**Comment by JaspreetGIT** [comment]
Yes I did. It just does not copy the Global Parameters list

**Comment by MeniKadosh1** [comment]
Bug # 7340 was raised for it.

**Comment by vyasprateek** [comment]
Hello @JaspreetGIT , Thank You for reporting the issue, it is fixed in the coming Beta version 3.2.2.

**Comment by vyasprateek** [comment]
Hello @JaspreetGIT , Thank You for reporting the issue, it is fixed in the coming Beta version 3.2.2.
