### ISSUE TITLE
Add Output Value in API Model Issue

### ISSUE THREAD

**Issue by JaspreetGIT** [Ginger-Automation/Ginger#788]
Create an API Model
Go to Output Tab, Add the Parameter there Result and expected output
Go to the business flow
Use the recently created Model Parameter
Check Output parameter tab

Expected:
The configured Parameter should appear with operator as Equals
Actual:
The configured Parameter should appear with operator as "Legacy"

**Comment by MeniKadosh1** [comment]
Bug # 7318 raised for it.

**Comment by ravirk91** [comment]
fixed in version 3.6.9
