### ISSUE TITLE
Action type show differently for data source in "Step actions" and execution report

### ISSUE THREAD

**Issue by Sunny-Teo** [Ginger-Automation/Ginger#793]
**Describe the bug**
Action type text is different in "Step Actions" and execution report.

**To Reproduce**
1. Add some action steps with Data Source action
2. Run the execution
3. Open the execution report
4. Compare action type for "Data Source Action" in steps action and execution report.

**Expected behavior**
Both should be same to avoid confusion.

**Screenshots**
![Action_Type_Issue](https://user-images.githubusercontent.com/25932794/55154837-d3ef1880-517b-11e9-91fd-fd2aa413dfba.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Also, if there is multiple execution based on data source, only the last execution snapshot is displayed in the report. However, with screenshot action we can take screenshots but report will only show the last iteration. Is it possible to have report for each iteration with snapshots?

**Comment by MeniKadosh1** [comment]
Regarding Action Type- the type is missing for Data Source Action and we will handle it for next Beta version 3.2.1.

Regarding seeing all iterations of the executed Actions- you need to set to have it in the HTML Report template configurations- see below how to set it:
![image](https://user-images.githubusercontent.com/40244398/55289215-20c92e00-53cc-11e9-988a-f7db3fbe5346.png)
