### ISSUE TITLE
Unable to find genkins plugin

### ISSUE THREAD

**Issue by Sunny-Teo** [Ginger-Automation/Ginger#840]
I was trying to integrate ginger with jenkins. In the help document, it was mentioned to use "gingerPlugin.hpi" plugin. I am not able to find this plugin. Is this plugin available or there is another way to integrate with jenkins.

![Jenkins Plugin](https://user-images.githubusercontent.com/25932794/56416938-03430200-62b0-11e9-9850-f8beb479198f.PNG)

I have tried to run the project from the below;-
https://github.com/Ginger-Automation/Ginger-Jenkins-Integration
Compiled with MVN and got the .hpi file. But its field are different from the help file and it is also not working. Please let me know if there is something I can do to execute it with genkins.

Output from Jenkins Console:-
Building in workspace D:\Jenkins\workspace\Ginger_Demo
Solution folder: C:\GingerSourceControl\Solutions\Test_Project\XXX_Automation
Run set name: Test Set 2
Target environment: Default
Ginger console folder: C:\Program Files (x86)\Amdocs\Ginger by amdocs
File C:\Program Files (x86)\Amdocs\Ginger by amdocs/config/201942502014-GingerParam.txt was created
command-dotnet C:\Program Files (x86)\Amdocs\Ginger by amdocs/GingerConsole.dll C:\Program Files (x86)\Amdocs\Ginger by amdocs/config/201942502014-GingerParam.txt
ERROR: Run set completed with failure
Finished: FAILURE

**Comment by Sunny-Teo** [comment]
I have tried to run the project from the below;-
https://github.com/Ginger-Automation/Ginger-Jenkins-Integration
Compiled with MVN and got the .hpi file. But its field are different from the help file and it is also not working. Please let me know if there is something I can do to execute it with genkins.

Output from Jenkins Console:-
Building in workspace D:\Jenkins\workspace\Ginger_Demo
Solution folder: C:\GingerSourceControl\Solutions\Test_Project\XXX_Automation
Run set name: Test Set 2
Target environment: Default
Ginger console folder: C:\Program Files (x86)\Amdocs\Ginger by amdocs
File C:\Program Files (x86)\Amdocs\Ginger by amdocs/config/201942502014-GingerParam.txt was created
command-dotnet  C:\Program Files (x86)\Amdocs\Ginger by amdocs/GingerConsole.dll C:\Program Files (x86)\Amdocs\Ginger by amdocs/config/201942502014-GingerParam.txt
ERROR: Run set completed with failure
Finished: FAILURE

**Comment by MeniKadosh1** [comment]
Sorry for late respond.
The Plugin for Jenkins was published only internally in Amdocs, i added it also to the GitHub project.
You can download it from below:

https://github.com/Ginger-Automation/Ginger-Jenkins-Integration/releases/download/v1.9/Ginger_Jenkins_Plugin_v1.9.hpi
